version: '3'

services:
    nginx-spa:
        container_name: nginx-spa
        build: ./docker/web/
        ports:
            - '8001:88'
        volumes:
            - ./app/:/var/www/
            - ./docker/web/nginx.conf:/etc/nginx/nginx.conf
        links:
            - app-spa

    app-spa:
        container_name: app-spa
        build: ./docker/php/
        command: /sbin/init
        privileged: true
        restart: always
        expose:
            - "9000"
        links:
            - db-spa
        volumes:
            - ./app/:/var/www/
            - ./docker/php/php.ini:/etc/php/7.4/fpm/php.ini
            - ./docker/php/www.conf:/etc/php/7.4/fpm/pool.d/www.conf

    db-spa:
        image: mysql:8.0
        container_name: db-spa
        environment:
            MYSQL_DATABASE: db-spa
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        ports:
        - "3308:3306"
        volumes:
        - ./docker/db/data:/var/lib/mysql
        - ./docker/db/sql:/docker-entrypoint-initdb.d